version: "2.19"

services:
  server:
    container_name: bot-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
    ports:
      - 8080:8080

  mongo-db:
    image: mongo:7
    container_name: ${DB_CONTAINER}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - subscriptions_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DB_CONTAINER}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 8081:8081

volumes:
  subscriptions_data:
